<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <title>SmartPass Events (XML/XSLT)</title>
        <link rel="stylesheet" href="../css/style.css"/>
      </head>
      <body>
        <div class="container section">
          <span class="hero-eyebrow">XML + XSLT Pipeline</span>
          <h1>Campus Events (from XML)</h1>
          <p class="lead">This page is generated by transforming <code>events.xml</code> with <code>events.xsl</code>. The XML is validated against <code>events.dtd</code>.</p>
          <table class="xml-event-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Event Name</th>
                <th>Category</th>
                <th>Date</th>
                <th>Time</th>
                <th>Venue</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="events/event">
                <xsl:sort select="date"/>
                <tr>
                  <td><xsl:value-of select="id"/></td>
                  <td><strong><xsl:value-of select="name"/></strong></td>
                  <td><span class="cat-pill">
                    <xsl:attribute name="data-cat">
                      <xsl:value-of select="category"/>
                    </xsl:attribute>
                    <xsl:value-of select="category"/>
                  </span></td>
                  <td><xsl:value-of select="date"/></td>
                  <td><xsl:value-of select="time"/></td>
                  <td><xsl:value-of select="venue"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
